
import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger
} from "@/components/ui/accordion";

const OilFAQ: React.FC = () => {
  return (
    <>
      <h2 className="text-3xl mt-8 mb-6 font-bold">FAQ</h2>
      
      <div className="space-y-4">
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger className="text-xl font-semibold text-left">
              Why is crude oil valuable?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                Crude oil, also known as "black gold", is a raw material that is highly valued due to its wide use in the production of everyday products 
                such as plastic, gasoline, rubber, synthetics, and more. Over generations, an increase in global population and quality of life has caused 
                consumption and demand for crude oil to increase. As a finite product with high demand, crude oil is therefore considered a valuable commodity.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-2">
            <AccordionTrigger className="text-xl font-semibold text-left">
              What is OPEC?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                OPEC stands for the Organisation of Petroleum Exporting Countries. There are currently 13 member countries within the group. According to the 
                OPEC statute, the purpose of the group is to coordinate and unify the petroleum policies of its member countries to ensure the stabilisation 
                of oil markets to secure an efficient, cost-effective, and regular supply of petroleum to consumers, a steady income to producers, and a fair 
                return on capital for those investing in the petroleum industry.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-3">
            <AccordionTrigger className="text-xl font-semibold text-left">
              How is the oil market regulated?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                The physical oil market is largely unregulated, as there are only a few corporations controlling the mining and refining processes before 
                exporting the product across the world. This oligopoly makes it harder for regulators to carry out regulatory checks in a transparent manner.
              </p>
              <p className="text-left mt-2">
                However, in general, federal and state agencies work to control the domestic oil market in the USA through energy and environmental-related 
                laws and policies. The Organisation of Petroleum Exporting Countries (OPEC) meets frequently to debate and decide on the production levels of 
                oil generated by each nation for the rest of the globe. OPEC uses a straightforward supply-and-demand mechanism to regulate the price of oil 
                by regulating output levels.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-4">
            <AccordionTrigger className="text-xl font-semibold text-left">
              Which countries produce the most oil in the world?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                According to data collected by the Energy Information Administration (EIA), total global oil production averages more than 100.61 million 
                barrels per day. The top five oil-producing nations, responsible for nearly half of the world's production of crude oil, are the USA, Saudi Arabia, 
                Russia, Canada, and China.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-5">
            <AccordionTrigger className="text-xl font-semibold text-left">
              Can I make money trading oil?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                Crude oil is the world's most traded commodity. From its high liquidity and volatility arise opportunities to trade the fluctuations for profit. 
                The degree to which trading crude oil can be beneficial for you depends on a variety of factors, including your level of trading expertise, your 
                ability to do an in-depth analysis and the market's current volatility.
              </p>
              <p className="text-left mt-2">
                For an indication of your potential to make a profit from oil markets, try trading oil using virtual funds using a free Axi demo account.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-6">
            <AccordionTrigger className="text-xl font-semibold text-left">
              What are the risks involved with oil trading?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                There are two main types of risk associated with oil trading.
              </p>
              <p className="text-left mt-2">
                The first is the risk associated with trading itself. Oil is a commodity that is traded on futures markets and offers a high degree of leverage. 
                Using high levels of leverage can be risky, as there is the potential to lose all of your investment. Traders should apply robust risk management 
                strategies whenever leverage is being considered.
              </p>
              <p className="text-left mt-2">
                The second important concern is related to oil itself. Oil prices can fluctuate because it is a commodity, and the price is heavily impacted by 
                broader supply and demand variables. For instance, a political decision or modification to environmental policies may result in a sudden drop in 
                oil prices.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-7">
            <AccordionTrigger className="text-xl font-semibold text-left">
              What are the most popular oil trading products?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                The top oil trading products include crude oil futures, crude oil spot markets, oil exchange-traded funds (ETFs), and oil CFDs. For a full list 
                of oil trading products, please refer to our Product Schedule.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-8">
            <AccordionTrigger className="text-xl font-semibold text-left">
              What are the oil trading market hours?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                The oil trading market is split up into two trading sessions: Brent crude oil and West Texas oil.
              </p>
              <p className="text-left mt-2">
                The trading hours for Brent crude oil are Monday–Friday, 01:00–22:59 GMT.<br />
                The trading hours for West Texas oil are Sunday–Friday, 18:00–16:59 EDT.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-9">
            <AccordionTrigger className="text-xl font-semibold text-left">
              How much money do you need to start trading oil?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                The amount of money needed to start trading oil will depend on your goals, the oil products you want to trade, and whether you want to trade 
                using leverage.
              </p>
              <p className="text-left mt-2">
                Alongside highly competitive spreads, Axi ensures low-cost trading by not charging brokerage fees and commissions on standard accounts. 
                This lowers the barriers of entry in terms of the amount of capital you need to begin trading commodities online, meaning you can start 
                with as little as $50.
              </p>
              <p className="text-left mt-2">
                When trading oil CFDs with Axi, you can enjoy low margins, allowing you to take advantage of leverage and use a small amount of capital 
                to gain full exposure to a trade. Note that while leverage offers the potential for large profits, it can also increase the risk of losses. 
                Please ensure robust risk management practices when applying leverage.
              </p>
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-10">
            <AccordionTrigger className="text-xl font-semibold text-left">
              What spreads and margin does Axi offer on oil trading?
            </AccordionTrigger>
            <AccordionContent className="text-white">
              <p className="text-left">
                Axi offers extremely competitive variable spreads on oil, with spreads changing throughout the day. To experience how spreads work in real time, 
                open a free demo account where you can practise your trading using virtual funds. The initial margin rate starts at 2% for oil cash CFDs and 
                oil futures CFDs.
              </p>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </>
  );
};

export default OilFAQ;
